/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import controllers.CourierController;
import javax.swing.JOptionPane;

/**
 *
 * @author tareq
 */
public class CourierAssignments extends javax.swing.JFrame {
    
    private CourierController controller = new CourierController();
    private String courierId;
    private String selectedOrderId = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CourierAssignments.class.getName());

    /**
     * Creates new form CourierAssignments
     */
     public CourierAssignments(String courierId) {
    initComponents();
    this.courierId = courierId;
    loadOrders();
    ordersTable.getSelectionModel().addListSelectionListener(e -> {
    if (!e.getValueIsAdjusting()) {

        int row = ordersTable.getSelectedRow();

        if (row != -1) {
            selectedOrderId = ordersTable.getValueAt(row, 0).toString();
        }
    }
});
}
     
     
     private void loadOrders() {

    var orders = controller.getMyOrders(courierId);

    String[] columns = {"Order ID", "Customer", "Date", "Status","priority"};
    Object[][] data = new Object[orders.size()][4];

    for (int i = 0; i < orders.size(); i++) {
        data[i][0] = orders.get(i).getOrderId();
        data[i][1] = orders.get(i).getCustomerId();
        data[i][2] = orders.get(i).getOrderDate();
        data[i][3] = orders.get(i).getStatus();
        data[i][4] = orders.get(i).getPriority();
    }

    ordersTable.setModel(new javax.swing.table.DefaultTableModel(data, columns));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ordersScrollPane = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("IBM Plex Mono", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My assignments");

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer", "Date", "Status", "Priority"
            }
        ));
        jScrollPane1.setViewportView(ordersTable);

        ordersScrollPane.add(jScrollPane1);

        jButton1.setText("Delivered");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Out for Delivery");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("X");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout titleLabelLayout = new javax.swing.GroupLayout(titleLabel);
        titleLabel.setLayout(titleLabelLayout);
        titleLabelLayout.setHorizontalGroup(
            titleLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLabelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 58, Short.MAX_VALUE))
            .addGroup(titleLabelLayout.createSequentialGroup()
                .addGroup(titleLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titleLabelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ordersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(titleLabelLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        titleLabelLayout.setVerticalGroup(
            titleLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLabelLayout.createSequentialGroup()
                .addGroup(titleLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titleLabelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jButton3))
                .addGap(30, 30, 30)
                .addComponent(ordersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(titleLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            if (selectedOrderId == null) {
        JOptionPane.showMessageDialog(this, "Select an order first");
        return;
     }

     controller.updateOrderStatus(selectedOrderId, "OUT_FOR_DELIVERY");
 
     JOptionPane.showMessageDialog(this, "Status updated");

     loadOrders();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (selectedOrderId == null) {
        JOptionPane.showMessageDialog(this, "Select an order first");
        return;
    }

    controller.updateOrderStatus(selectedOrderId, "DELIVERED");

    JOptionPane.showMessageDialog(this, "Order delivered");

    loadOrders();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.ScrollPane ordersScrollPane;
    private javax.swing.JTable ordersTable;
    private javax.swing.JPanel titleLabel;
    // End of variables declaration//GEN-END:variables
}
