
package ui;

import controllers.TrackOrderController;
import model.Order;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author Yousif hafez
 */





public class TrackOrderFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TrackOrderFrame.class.getName());

  

 
 public TrackOrderFrame() {
    initComponents();

    String customerId = "CU001";

    loadOrders(customerId);

    RefreshOrder.addActionListener(e -> loadOrders(customerId));

    OrderTable.getSelectionModel().addListSelectionListener(e -> {
        int selectedRow = OrderTable.getSelectedRow();

        if (selectedRow != -1) {
            String orderId = OrderTable.getValueAt(selectedRow, 0).toString();
            showOrderDetails(orderId);
        }
    });
}
 
 
 
 private void showOrderDetails(String orderId) {
    TrackOrderController controller = new TrackOrderController();
    Order order = controller.getOrderStatus(orderId);
    if (order != null) {
        OrderIdValue.setText(order.getOrderId());
        StatusValue.setText(order.getStatus().toString());
        AddressValue.setText(order.getDeliveryAddress());
        CurrentStatusValue.setText(order.getStatus().toString());
        LastUpdatedValue.setText(order.getOrderDate() != null ? order.getOrderDate() : "N/A");
    }
}
 
 
 
 
 
 
private void loadOrders(String customerId) {
    TrackOrderController controller = new TrackOrderController();
    List<Order> orders = controller.getOrderHistory(customerId);
    DefaultTableModel model = (DefaultTableModel) OrderTable.getModel();
    model.setRowCount(0);
    for (Order order : orders) {
        model.addRow(new Object[]{
            order.getOrderId(),
            order.getStatus().toString(),
            order.getOrderDate(),
            order.getOrderDate() != null ? order.getOrderDate() : "N/A"
        });
    }
}
          
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TrackOrderStatus = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        OrderID = new javax.swing.JLabel();
        OrderIdValue = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        StatusValue = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        AddressValue = new javax.swing.JLabel();
        CurrentStatus = new javax.swing.JLabel();
        CurrentStatusValue = new javax.swing.JLabel();
        LastUpdated = new javax.swing.JLabel();
        LastUpdatedValue = new javax.swing.JLabel();
        RefreshOrder = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TrackOrderStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TrackOrderStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TrackOrderStatus.setText("Track Order Status");

        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID:", "Status", "Order Date", "Last Updated"
            }
        ));
        OrderTable.setShowGrid(true);
        jScrollPane2.setViewportView(OrderTable);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Order Details"));

        OrderID.setBackground(new java.awt.Color(0, 0, 0));
        OrderID.setText("Order ID:");

        OrderIdValue.setText("----------");

        Status.setText("Status:");

        StatusValue.setText("----------");

        Address.setText("Address:");

        AddressValue.setText("---------");

        CurrentStatus.setText("Current Status:");

        CurrentStatusValue.setText("---------");

        LastUpdated.setText("Last Updated:");

        LastUpdatedValue.setText("----------");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(OrderID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OrderIdValue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(StatusValue, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Address)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddressValue))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CurrentStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CurrentStatusValue))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LastUpdated)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LastUpdatedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(OrderIdValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OrderID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Status)
                    .addComponent(StatusValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address)
                    .addComponent(AddressValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrentStatus)
                    .addComponent(CurrentStatusValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LastUpdated)
                    .addComponent(LastUpdatedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        RefreshOrder.setText("Refresh Order");
        RefreshOrder.addActionListener(this::RefreshOrderActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(TrackOrderStatus)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(RefreshOrder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TrackOrderStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RefreshOrder)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshOrderActionPerformed
       loadOrders("CU001");
    }//GEN-LAST:event_RefreshOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

   java.awt.EventQueue.invokeLater(() -> {
       new TrackOrderFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel AddressValue;
    private javax.swing.JLabel CurrentStatus;
    private javax.swing.JLabel CurrentStatusValue;
    private javax.swing.JLabel LastUpdated;
    private javax.swing.JLabel LastUpdatedValue;
    private javax.swing.JLabel OrderID;
    private javax.swing.JLabel OrderIdValue;
    private javax.swing.JTable OrderTable;
    private javax.swing.JButton RefreshOrder;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel StatusValue;
    private javax.swing.JLabel TrackOrderStatus;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
